/**
 * Gemini Content Generation Service
 * Generates article titles and tags using Google's Gemini AI
 */

// @ts-ignore - Vite env types
const GEMINI_API_KEY = import.meta.env?.VITE_GOOGLE_API_KEY;
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent';

interface ContentSuggestions {
  title: string;
  tags: string[];
  excerpt?: string;
}

/**
 * Generate article title and tags based on content
 */
export async function generateArticleMetadata(
  articleBody: string,
  region?: string,
  category?: string
): Promise<ContentSuggestions> {
  if (!GEMINI_API_KEY) {
    throw new Error('Google AI API key not configured');
  }

  if (!articleBody || articleBody.trim().length < 100) {
    throw new Error('Article content is too short to generate metadata');
  }

  const prompt = `You are a professional financial journalism editor for "The Mane Review", a prestigious financial publication.

Analyse the following article content and generate:
1. A compelling, professional title (in British English, 8-12 words, capitalise major words)
2. 3-5 relevant tags (single words or short phrases, in British English, related to finance, markets, investing)
3. A brief excerpt (20-30 words, in British English)

Article Category: ${category || 'Opinion'}
Regional Focus: ${region || 'Global'}

Article Content:
${articleBody.substring(0, 2000)}

Requirements:
- Title must be engaging, professional, and SEO-friendly
- Title should capture the main thesis or insight
- Tags must be relevant to finance/markets/investing
- Tags should include: topic keywords, market sectors, geographic regions if relevant
- Use British English spelling (e.g., "analyse" not "analyze", "favour" not "favor")
- Be specific and avoid generic terms
- Focus on investment themes, market trends, economic concepts

Respond ONLY with valid JSON in this exact format:
{
  "title": "Your Generated Title Here",
  "tags": ["Tag1", "Tag2", "Tag3", "Tag4", "Tag5"],
  "excerpt": "Your generated excerpt here."
}`;

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 500,
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('[Gemini Content] API Error:', errorData);
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    console.log('[Gemini Content] Raw response:', data);

    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!generatedText) {
      throw new Error('No content generated by Gemini');
    }

    // Extract JSON from the response (handle markdown code blocks)
    let jsonText = generatedText.trim();
    if (jsonText.startsWith('```json')) {
      jsonText = jsonText.replace(/```json\n?/g, '').replace(/```\n?/g, '');
    } else if (jsonText.startsWith('```')) {
      jsonText = jsonText.replace(/```\n?/g, '');
    }

    const suggestions: ContentSuggestions = JSON.parse(jsonText);

    // Validate the response
    if (!suggestions.title || !Array.isArray(suggestions.tags)) {
      throw new Error('Invalid response format from Gemini');
    }

    // Clean up tags (remove duplicates, limit to 5)
    suggestions.tags = [...new Set(suggestions.tags)]
      .slice(0, 5)
      .map(tag => tag.trim())
      .filter(tag => tag.length > 0);

    console.log('[Gemini Content] Generated suggestions:', suggestions);
    return suggestions;

  } catch (error) {
    console.error('[Gemini Content] Error:', error);
    throw error;
  }
}

/**
 * Generate only tags based on article content
 */
export async function generateArticleTags(
  articleBody: string,
  region?: string,
  category?: string
): Promise<string[]> {
  const suggestions = await generateArticleMetadata(articleBody, region, category);
  return suggestions.tags;
}

/**
 * Generate only title based on article content
 */
export async function generateArticleTitle(
  articleBody: string,
  region?: string,
  category?: string
): Promise<string> {
  const suggestions = await generateArticleMetadata(articleBody, region, category);
  return suggestions.title;
}

/**
 * Check if Gemini API is configured
 */
export function isGeminiConfigured(): boolean {
  return !!GEMINI_API_KEY;
}
