import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Badge } from '../ui/badge';
import { Separator } from '../ui/separator';
import { Target, Heart, Users, BookOpen, Shield, Mail, Award, TrendingUp } from 'lucide-react';

interface AboutPageProps { onNavigate: (page: string, data?: any) => void; }

export function AboutPage({ onNavigate }: AboutPageProps) {
  return (
    <div className="container mx-auto px-4 py-12 space-y-16">
      <div className="text-center space-y-8"><h1 className="font-bold text-primary leading-none mb-6" style={{ fontFamily: 'var(--font-headline)', fontSize: '30px' }}>About The Mane Review</h1><p className="text-muted-foreground max-w-2xl mx-auto">Making markets approachable for anyone interested in investing, finance, and economic thinking.</p></div>
      <section className="space-y-10"><Card><CardHeader><CardTitle className="flex items-center space-x-2"><Target className="h-6 w-6 text-secondary" /><span>What We Are</span></CardTitle></CardHeader><CardContent className="space-y-6"><p className="text-muted-foreground leading-relaxed">The Mane Review is an educational financial publication created by students at St. Paul's School. We bridge the gap between complex market analysis and accessible investment education, providing thoughtful commentary on global markets, emerging trends, and investment opportunities across major economies.</p><p className="text-muted-foreground leading-relaxed">As students passionate about finance and investing, our platform serves as both a learning resource for those new to investing and a source of fresh perspectives for experienced market participants. We cover markets in Brazil, the USA, Europe, and Asia, offering regional insights and global context.</p><div className="flex flex-wrap gap-3 mt-6"><Badge className="bg-secondary text-secondary-foreground">Educational Content</Badge><Badge variant="outline">Global Markets</Badge><Badge variant="outline">Investment Analysis</Badge><Badge variant="outline">Student Perspectives</Badge></div></CardContent></Card></section>
      <section className="space-y-10"><Card><CardHeader><CardTitle className="flex items-center space-x-2"><Mail className="h-6 w-6 text-secondary" /><span>Contact Us</span></CardTitle></CardHeader><CardContent className="space-y-6"><p className="text-muted-foreground">We'd love to hear from you. Whether you have questions, feedback, or ideas for collaboration, don't hesitate to reach out.</p><div className="grid md:grid-cols-2 gap-4"><div className="space-y-3"><h5 className="font-medium">General Enquiries</h5><a href="mailto:hg3@stpauls.br" className="flex items-center gap-2 p-3 border rounded-lg hover:bg-muted/50 transition-colors"><Mail className="h-4 w-4 text-muted-foreground" /><span className="text-sm">hg3@stpauls.br</span></a></div><div className="space-y-3"><h5 className="font-medium">Article Submissions & Joining Our Team</h5><a href="mailto:hg3@stpauls.br" className="flex items-center gap-2 p-3 border rounded-lg hover:bg-muted/50 transition-colors"><Mail className="h-4 w-4 text-muted-foreground" /><span className="text-sm">hg3@stpauls.br</span></a><p className="text-xs text-muted-foreground">Contact us to submit articles or join The Mane Review</p></div></div></CardContent></Card></section>
    </div>
  );
}