import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const GOOGLE_API_KEY = Deno.env.get('GOOGLE_API_KEY')
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface MetadataRequest {
  articleBody: string
  region?: string
  category?: string
}

interface MetadataResponse {
  title: string
  tags: string[]
  excerpt?: string
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (!GOOGLE_API_KEY) {
      throw new Error('GOOGLE_API_KEY not configured')
    }

    const { articleBody, region, category }: MetadataRequest = await req.json()

    if (!articleBody || articleBody.trim().length < 100) {
      throw new Error('Article content is too short (minimum 100 characters)')
    }

    const prompt = `You are a professional financial journalism editor for "The Mane Review", a prestigious financial publication.

Analyse the following article content and generate:
1. A compelling, professional title (in British English, 8-12 words, capitalise major words)
2. 3-5 relevant tags (single words or short phrases, in British English, related to finance, markets, investing)
3. A brief excerpt (20-30 words, in British English)

Article Category: ${category || 'Opinion'}
Regional Focus: ${region || 'Global'}

Article Content:
${articleBody.substring(0, 2000)}

Requirements:
- Title must be engaging, professional, and SEO-friendly
- Title should capture the main thesis or insight
- Tags must be relevant to finance/markets/investing
- Tags should include: topic keywords, market sectors, geographic regions if relevant
- Use British English spelling (e.g., "analyse" not "analyze", "favour" not "favor")
- Be specific and avoid generic terms
- Focus on investment themes, market trends, economic concepts

Respond ONLY with valid JSON in this exact format:
{
  "title": "Your Generated Title Here",
  "tags": ["Tag1", "Tag2", "Tag3", "Tag4", "Tag5"],
  "excerpt": "Your generated excerpt here."
}`

    console.log('[Gemini Metadata] Calling Gemini API...')

    const response = await fetch(`${GEMINI_API_URL}?key=${GOOGLE_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 500,
        }
      })
    })

    if (!response.ok) {
      const errorData = await response.json()
      console.error('[Gemini Metadata] API Error:', errorData)
      throw new Error(`Gemini API error: ${response.status}`)
    }

    const data = await response.json()
    console.log('[Gemini Metadata] Raw response:', data)

    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text
    if (!generatedText) {
      throw new Error('No content generated by Gemini')
    }

    // Extract JSON from the response (handle markdown code blocks)
    let jsonText = generatedText.trim()
    if (jsonText.startsWith('```json')) {
      jsonText = jsonText.replace(/```json\n?/g, '').replace(/```\n?/g, '')
    } else if (jsonText.startsWith('```')) {
      jsonText = jsonText.replace(/```\n?/g, '')
    }

    const suggestions: MetadataResponse = JSON.parse(jsonText)

    // Validate the response
    if (!suggestions.title || !Array.isArray(suggestions.tags)) {
      throw new Error('Invalid response format from Gemini')
    }

    // Clean up tags (remove duplicates, limit to 5)
    suggestions.tags = [...new Set(suggestions.tags)]
      .slice(0, 5)
      .map(tag => tag.trim())
      .filter(tag => tag.length > 0)

    console.log('[Gemini Metadata] Generated suggestions:', suggestions)

    return new Response(
      JSON.stringify(suggestions),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    )

  } catch (error) {
    console.error('[Gemini Metadata] Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      }
    )
  }
})
