import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

const GOOGLE_API_KEY = Deno.env.get('VITE_GOOGLE_API_KEY') || Deno.env.get('GOOGLE_API_KEY')
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite-preview-09-2025:generateContent'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface FormatRequest {
  articleBody: string
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (!GOOGLE_API_KEY) {
      throw new Error('GOOGLE_API_KEY not configured')
    }

    const { articleBody }: FormatRequest = await req.json()

    if (!articleBody || articleBody.trim().length < 100) {
      throw new Error('Article content is too short')
    }

    // Check if already formatted
    if (articleBody.includes('# ') || articleBody.includes('## ')) {
      console.log('[Auto Format] Article already has formatting, skipping')
      return new Response(
        JSON.stringify({ formattedBody: articleBody, wasFormatted: false }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      )
    }

    const prompt = `You are a professional editor for "The Mane Review", a financial publication.

Your task is to add professional formatting to this article by identifying natural sections and adding appropriate headings.

RULES:
1. Add ## (H2) headings for major sections (2-4 sections total)
2. Add ### (H3) headings for subsections if needed
3. Keep the EXACT same content - only add headings, don't change the text
4. Headings should be clear, descriptive, and professional
5. Use British English for headings
6. Don't add a main title (# H1) - that's already set
7. Preserve all paragraphs exactly as they are
8. Add **bold** to 3-5 key terms or phrases throughout the article for emphasis
9. Separate paragraphs with blank lines

Article to format:
${articleBody}

Return ONLY the formatted article text with headings added. No explanations, no JSON, just the formatted text.`

    console.log('[Auto Format] Calling Gemini API...')

    const response = await fetch(`${GEMINI_API_URL}?key=${GOOGLE_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.3,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 4000,
        }
      })
    })

    if (!response.ok) {
      const errorData = await response.json()
      console.error('[Auto Format] API Error:', errorData)
      throw new Error(`Gemini API error: ${response.status}`)
    }

    const data = await response.json()
    console.log('[Auto Format] Response received')

    const formattedText = data.candidates?.[0]?.content?.parts?.[0]?.text
    if (!formattedText) {
      throw new Error('No content generated by Gemini')
    }

    // Clean up any markdown code blocks if present
    let cleanedText = formattedText.trim()
    if (cleanedText.startsWith('```')) {
      cleanedText = cleanedText.replace(/```[a-z]*\n?/g, '').replace(/```\n?/g, '')
    }

    console.log('[Auto Format] Formatting completed successfully')

    return new Response(
      JSON.stringify({ 
        formattedBody: cleanedText.trim(),
        wasFormatted: true 
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    )

  } catch (error) {
    console.error('[Auto Format] Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      }
    )
  }
})
